### PR TITLE
Add JSCS & JSHint

### PR DESCRIPTION
**Pull request by SimenB**
Do you want JSHint as well/instead?

### CODE REVIEW

**Comment by lazd** [comment]
JSHint is helpful in development, so it would be a nice addition, but this is good enough for now!

You really are on a roll!

**Comment by SimenB** [comment]
@lazd Added JSHint as well. I have no idea what rules you want, so I just chucked in a couple :smile:

**Comment by lazd** [comment]
Very cool, I'll configure 'em.

**Comment by SimenB** [comment]
@lazd ping :smile:

**Pull request merged**
