### PR TITLE
Adding addRule function

### PR DESCRIPTION
**Pull request by lukasoppermann**
Users should be able to add their own rules, just like with the csslint plugin. This solves #24

### CODE REVIEW

**Comment by SimenB** [comment]
@lukasoppermann Code style check failed. Seems I messed up in #22 and don't fail the build...

**Comment by lukasoppermann** [comment]
@SimenB sorry, I don't get it, do I need to fix/change something?

**Comment by SimenB** [comment]
run `npm test` locally

**Comment by lukasoppermann** [comment]
@SimenB ahh, now I get it, fixed the missing space. thanks.

**Comment by SimenB** [comment]
@lukasoppermann Seems there's no rule for it, but braces in general are on same line as conditionals in this source code.

No JSCS rule for it though...

```js
if (condition) {
```
not 
```js
if (condition)
  {
```

@lazd I just hijacked this, whoop! Could you update the rc's to be more strict maybe? Or do you want me to do it?

**Comment by lukasoppermann** [comment]
@SimenB so how is else?

Option 1:
```javascript
} else {
```
or Option 2:
```javascript
}
else {

**Comment by SimenB** [comment]
@lukasoppermann That I don't know. Doesn't seem to be any other `else`s...
@lazd will have to answer that one.

How about adding `"disallowNewlineBeforeBlockStatements": true` to `.jscsrc`?

**Comment by lukasoppermann** [comment]
@SimenB I just removed the need for else.

**Comment by SimenB** [comment]
@lukasoppermann A, nice!

**Comment by lazd** [comment]
@lukasoppermann Add some documentation to README and we can merge this!

**Comment by lukasoppermann** [comment]
Hey @lazd I added the docs, but the coverage stuff now freaked. :) Wasn't there before, I just changed the readme.

**Comment by SimenB** [comment]
Yeah, we just added test-coverage from Coveralls yesterday. You could add a test? :smiley:

**Comment by lukasoppermann** [comment]
@SimenB had a look but I have no idea how to write a test for this. I do not have much experience with gulp plugins.

**Comment by lazd** [comment]
I think the best way to test this is to provide a fixture that passes with the default ruleset, but fails with a rule that you add using the new API. Then, run that fixture against the plugin and `expect` an error.

**Comment by lukasoppermann** [comment]
Hey, my problem is rather that I can not write the complete test, because writing a test for a gulp plugin is something I don't know how to do. Can you just merge it and write the test? You seem to have a pretty good idea of how to do it, so I guess you could wip up a test within a minute or so.

**Comment by lazd** [comment]
@lukasoppermann, it's pretty easy, and there's no better time to learn than now :) Just look at the existing tests and modify one to fit your needs.

[This test](https://github.com/lazd/gulp-csslint/blob/master/test/main.js#L67-L86) expects something to fail, so you can copy paste it, use a different fixture, invoke your new `addRule` function inside of it, and be done.

**Comment by lukasoppermann** [comment]
@lazd I added a test, but I can't get it to work the whole gulp thing is just over the top for me. 
It should fail if your class name does not start with something like `.o-object` but it always passes. ;(

Please help.

**Comment by SimenB** [comment]
@lukasoppermann Does it fail runtime? As in actually adding that rule and running against a real codebase?

I'm really bad at regexp, but from what I understand, the last part (allowing alphanumerics) is wrong, and only matches one char.

```js
'.o-foo'.match(/^\.(_)?(o|c|u|is|has|js|qa)-[a-z0-9]$/)
 > null
```



```js
'.o-f'.match(/^\.(_)?(o|c|u|is|has|js|qa)-[a-z0-9]$/)
 > [".o-f", undefined, "o"]
```

**Comment by lukasoppermann** [comment]
@SimenB thanks for catching it. Actually my problem was a wrong css file. This is why it did not report and error, which means not passing the test. :)

**Comment by SimenB** [comment]
Ah, OK. Nice you got it running.

Travis seems to have problems `npm install`ing atm

**Comment by lazd** [comment]
I restarted the build and all is well. Looks good, thanks for the contribution!

**Comment by lukasoppermann** [comment]
Hey, could you maybe release a version with this merge in it?

**Pull request merged**
