### PR TITLE
Removing the assumption that the cssLint config is in the cwd

### LINKED ISSUE #13: Don't assume './' when loading the cssLint config
If you use the `--cwd` flag in the gulp cli, it can cause some headaches/confusion. Should allow for absolute paths. Assuming the cssLint config is in the current directory potentially leads to stuff like this:

```javascript
module.exports = gulp.task( 'css', function() {
    'use strict';

    return gulp.src( src.lib + 'less/' + src.project + '.less' )
        .pipe( less())
        .pipe( csslint( '../../../../.csslintrc' ))
        .pipe( csslint.reporter())
        .pipe( gulp.dest( cwd + 'lib/css/' ));
});
```

### PR DESCRIPTION
**Pull request by mike-engel**
This would fix #13.

### CODE REVIEW

**Comment by lazd** [comment]
Hey @mike-engel, sorry it took me so long to get around to this.

Seems simple enough, but one question: does it break stuff?

**Comment by mike-engel** [comment]
@lazd I haven't fully tested it. In theory though, it *shouldn't*. The only caveat I could see is that if someone was just specifying a file in the current directory without the `./`, I don't know if the `fs` module will read the right file. Does that make sense?

**Comment by lazd** [comment]
Yeah, that makes sense. It might still work, I'd have to test it to know, honestly, and it may depend on where you invoke gulp from...

**Comment by lazd** [comment]
@mike-engel what do you think about https://github.com/lazd/gulp-csslint/pull/17 ?

**Comment by mike-engel** [comment]
@lazd Works for me!

**Pull request closed without merging**
