### PR TITLE
Update to CSSLint v1

### PR DESCRIPTION
**Pull request by SimenB**
The test introduced in #42 fails, unsure why.

/cc @betaorbust Any ideas?

### CODE REVIEW

**Comment by betaorbust** [comment]
#42 was around the leaking of directive/rules across files,
I'd suggest a small repro case, where you have:
`fileA.css`
```css
/*csslint duplicate-properties:false*/
.no-leak-1{
  height: 42px;
  width: 0px;
  height: 21px;
}
```
and `fileB.css`
```css
.no-leak-2{
  height: 42px;
  width: 0px;
  height: 21px;
}
```
If you run your branch against that, using a glob that selects first `fileA` and then `fileB` (in the same run) does `fileB` fail linting? If not, the cross-file leak issue has returned.
Ideally, that's what the test is checking for, but perhaps there are new edge cases introduced in the move to v1, that my original test failed to take into account?

**Comment by SimenB** [comment]
Hmm, seems to be a new violation on the files: 
image

**Comment by SimenB** [comment]
@betaorbust OK, passing now. Is the change a good one you think?

**Comment by SimenB** [comment]
@lazd This should be GTG now I think, if the changes to the test is OK. THEN I think it's time for 1.0.0 😄

**Comment by betaorbust** [comment]
Sorry for the long delay. Change looks good.

**Comment by lazd** [comment]
Woot! I'll merge this and release 1.0.0

**Comment by Spunkie** [comment]
@lazd With all the PRs finally merged in can we expect a new major version release on NPM?

**Comment by lazd** [comment]
@Spunkie you don't have to expect it, it's published! Thanks to @SimenB, @betaorbust, and everyone else that helped out, `gulp-csslint@1.0.0` is available now!

**Pull request merged**
