### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by SimenB**
Only csslint not bumped to 1 and eslint not bumped to 3. First because I'm unsure of breaking changes, second because semistandard still uses eslint@2

### CODE REVIEW

**Comment by SimenB** [comment]
@lazd Bumped eslint dep as well, only old one now is csslint.

**Comment by lazd** [comment]
@SimenB looks like merging the most recent PRs broke this one, if it's still relevant, rebase and I'll get it merged in. Thanks!

**Comment by SimenB** [comment]
@lazd Updated 😄

**Comment by SimenB** [comment]
I did CSSLint@1 in its own PR, as it makes the tests fail (with or without the changes in this PR)

**Pull request merged**
